"""initial_schema_with_auth_and_integrations

Revision ID: e626b43574df
Revises:
Create Date: 2026-06-27 20:40:04.649491

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = "e626b43574df"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ── Step 1: Enable PostgreSQL extensions ──────────────────────────────────
    # These MUST run before any table that uses vector or UUID types.
    # pgvector: adds the 'vector' column type for similarity search.
    # uuid-ossp: adds uuid_generate_v4() (used by some legacy code).
    # "IF NOT EXISTS" makes this idempotent — safe to run multiple times.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "third_party_integrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "name",
            sa.Text(),
            nullable=False,
            comment="Slug: 'github' | 'jira' | 'google'. Used as identifier in code.",
        ),
        sa.Column(
            "display_name",
            sa.Text(),
            nullable=False,
            comment="Human-readable name shown in UI: 'GitHub', 'Jira Cloud'.",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Short description shown in the connect UI.",
        ),
        sa.Column(
            "logo_url",
            sa.Text(),
            nullable=True,
            comment="URL to the service's logo. Shown in connect UI.",
        ),
        sa.Column(
            "auth_type",
            sa.Text(),
            nullable=False,
            comment="'oauth2' or 'pat' (Personal Access Token). Determines the connect flow.",
        ),
        sa.Column(
            "oauth_authorize_url",
            sa.Text(),
            nullable=True,
            comment="Where to redirect the user to start OAuth. GitHub: 'https://github.com/login/oauth/authorize'",
        ),
        sa.Column(
            "oauth_token_url",
            sa.Text(),
            nullable=True,
            comment="Where to exchange the OAuth code for an access token.",
        ),
        sa.Column(
            "required_scopes",
            sa.Text(),
            nullable=True,
            comment="Space or comma-separated OAuth scopes we request. GitHub: 'repo read:user', Google: 'drive.readonly'",
        ),
        sa.Column(
            "docs_url",
            sa.Text(),
            nullable=True,
            comment="Link to our setup guide for this integration.",
        ),
        sa.Column(
            "is_enabled",
            sa.Boolean(),
            nullable=False,
            comment="FALSE = integration hidden from UI. Useful for maintenance.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_third_party_integrations_name"),
        "third_party_integrations",
        ["name"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            nullable=False,
            comment="UUID v4 primary key — not guessable, safe to expose in URLs",
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="Primary login identifier. Indexed for fast lookup.",
        ),
        sa.Column(
            "password_hash",
            sa.Text(),
            nullable=True,
            comment="bcrypt hash of password. NULL for future OAuth-only accounts.",
        ),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("middle_name", sa.Text(), nullable=True),
        sa.Column(
            "last_name",
            sa.Text(),
            nullable=True,
            comment="Nullable — mononyms exist (Adele, Madonna, Sukarno).",
        ),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="FALSE = soft-disabled account. Still exists in DB for audit trail.",
        ),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            nullable=False,
            comment="Gate for email confirmation flow.",
        ),
        sa.Column(
            "last_login_at",
            sa.String(),
            nullable=True,
            comment="Updated on every successful login. Used for security auditing.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="SET NULL: if user deletes account, PRs remain for audit. NULL = submitted anonymously (before auth was implemented).",
        ),
        sa.Column(
            "pr_url", sa.Text(), nullable=False, comment="The GitHub Pull Request URL."
        ),
        sa.Column(
            "jira_url",
            sa.Text(),
            nullable=True,
            comment="Optional. Jira ticket for requirements context.",
        ),
        sa.Column(
            "doc_url",
            sa.Text(),
            nullable=True,
            comment="Optional. Google Doc for design/feature context.",
        ),
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment="queued | collecting | analyzing | consensus | awaiting_human | complete | failed | cancelled",
        ),
        sa.Column(
            "risk_score",
            sa.Integer(),
            nullable=True,
            comment="0–100. Set by Consensus Agent. NULL until consensus completes.",
        ),
        sa.Column(
            "recommendation",
            sa.Text(),
            nullable=True,
            comment="approve | approve_with_comments | request_changes | block",
        ),
        sa.Column(
            "llm_provider",
            sa.Text(),
            nullable=True,
            comment="gemini | openai | ollama | anthropic",
        ),
        sa.Column(
            "llm_model",
            sa.Text(),
            nullable=True,
            comment="e.g. 'gemini-2.5-flash', 'gpt-4o', 'llama3.1'",
        ),
        sa.Column(
            "task_id",
            sa.Text(),
            nullable=True,
            comment="Celery task ID. Used to terminate the task via celery.control.revoke().",
        ),
        sa.Column(
            "error",
            sa.Text(),
            nullable=True,
            comment="Full error message if status='failed'.",
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pull_requests_status"), "pull_requests", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_pull_requests_user_id"), "pull_requests", ["user_id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="CASCADE: deleting a user deletes all their sessions.",
        ),
        sa.Column(
            "token_hash",
            sa.Text(),
            nullable=False,
            comment="SHA-256 hash of the raw refresh token. Never store the raw token.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="30 days from creation. Token invalid after this.",
        ),
        sa.Column(
            "revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="NULL = still valid. Set on logout or suspicious activity.",
        ),
        sa.Column(
            "device_info",
            sa.Text(),
            nullable=True,
            comment='e.g. "Chrome 125 on macOS 15". For session management UI.',
        ),
        sa.Column(
            "ip_address",
            sa.Text(),
            nullable=True,
            comment="IP at time of login. For security alerts.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "third_party_user_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("integration_id", sa.UUID(), nullable=False),
        sa.Column(
            "access_token_encrypted",
            sa.Text(),
            nullable=False,
            comment="AES-256 encrypted access token. NOT NULL — every integration always needs this.",
        ),
        sa.Column(
            "credentials",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="Provider-specific optional credentials as JSONB. Keys: refresh_token (encrypted), expires_at, site_url (Jira), cloud_id (Jira).",
        ),
        sa.Column(
            "provider_user_id",
            sa.Text(),
            nullable=True,
            comment="Their ID on that platform. GitHub numeric ID, Google 'sub', Atlassian account ID.",
        ),
        sa.Column(
            "provider_email",
            sa.Text(),
            nullable=True,
            comment="Email on that platform (may differ from AERP email).",
        ),
        sa.Column(
            "provider_username",
            sa.Text(),
            nullable=True,
            comment="Display name on platform, e.g. GitHub username.",
        ),
        sa.Column(
            "granted_scopes",
            sa.Text(),
            nullable=True,
            comment="Scopes the user actually approved. May be subset of required_scopes.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="FALSE = user disconnected this integration. Row kept for audit.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["integration_id"], ["third_party_integrations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "integration_id", name="uq_user_integration"),
    )
    op.create_index(
        op.f("ix_third_party_user_accounts_user_id"),
        "third_party_user_accounts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pull_request_id", sa.UUID(), nullable=False),
        sa.Column(
            "merged_into_id",
            sa.UUID(),
            nullable=True,
            comment="Self-referential FK. When status='merged_duplicate', this points to the canonical comment that absorbed this one.",
        ),
        sa.Column(
            "agent",
            sa.Text(),
            nullable=False,
            comment="Which agent generated this. e.g. 'security_agent', 'code_review_agent'",
        ),
        sa.Column(
            "severity",
            sa.Text(),
            nullable=False,
            comment="critical | high | medium | low | info",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=False,
            comment="0.0–1.0. Findings below threshold get status='filtered_low_confidence'.",
        ),
        sa.Column(
            "title",
            sa.Text(),
            nullable=False,
            comment="Short, specific issue title (max ~80 chars).",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Full explanation: what, why, impact.",
        ),
        sa.Column(
            "evidence",
            sa.Text(),
            nullable=False,
            comment="The exact code snippet that triggered this finding.",
        ),
        sa.Column(
            "suggested_fix",
            sa.Text(),
            nullable=True,
            comment="Corrected code snippet or remediation steps.",
        ),
        sa.Column(
            "file_path",
            sa.Text(),
            nullable=True,
            comment="e.g. 'backend/api/routes/payments.py'",
        ),
        sa.Column(
            "line_number",
            sa.Integer(),
            nullable=True,
            comment="Specific line in the file.",
        ),
        sa.Column(
            "owasp_category",
            sa.Text(),
            nullable=True,
            comment="For security findings only. e.g. 'A03:2021 - Injection'",
        ),
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment="pending | included | filtered_low_confidence | merged_duplicate | false_positive",
        ),
        sa.Column(
            "is_posted_to_github",
            sa.Boolean(),
            nullable=False,
            comment="TRUE only after the GitHub API call succeeds.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"], ["comments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comments_pull_request_id"),
        "comments",
        ["pull_request_id"],
        unique=False,
    )
    op.create_index(op.f("ix_comments_status"), "comments", ["status"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "pull_request_id",
            sa.UUID(),
            nullable=False,
            comment="All embeddings are scoped to a specific PR analysis.",
        ),
        sa.Column(
            "source",
            sa.Text(),
            nullable=False,
            comment="github_pr | jira | google_doc | repo_file",
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
            comment="The raw text chunk that was embedded. What humans read.",
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment='{"file": "payments.py", "lines": "44-58", "chunk_index": 3}',
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            nullable=True,
            comment="768-dimensional float vector from Google text-embedding-004. The HNSW index on this column enables fast similarity search. NULL only transiently, while embedding is being computed.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embeddings_pull_request_id"),
        "embeddings",
        ["pull_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embeddings_source"), "embeddings", ["source"], unique=False
    )
    op.create_table(
        "human_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pull_request_id", sa.UUID(), nullable=False),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=True,
            comment="SET NULL: record preserved even if user account is deleted.",
        ),
        sa.Column(
            "decision",
            sa.Text(),
            nullable=False,
            comment="approve | reject | approve_with_override",
        ),
        sa.Column(
            "reviewer_name",
            sa.Text(),
            nullable=False,
            comment="Immutable snapshot of the reviewer's name at decision time. NOT a FK join — audit records must not change if user renames.",
        ),
        sa.Column(
            "comment",
            sa.Text(),
            nullable=True,
            comment="Optional human reasoning for the decision.",
        ),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Exact moment the human clicked Approve or Reject.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_human_decisions_pull_request_id"),
        "human_decisions",
        ["pull_request_id"],
        unique=False,
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pull_request_id", sa.UUID(), nullable=False),
        sa.Column(
            "agent_name",
            sa.Text(),
            nullable=False,
            comment="Which agent or system component sent this log.",
        ),
        sa.Column(
            "status",
            sa.Text(),
            nullable=False,
            comment="running | complete | failed | skipped",
        ),
        sa.Column(
            "message",
            sa.Text(),
            nullable=False,
            comment="The log line displayed in the dashboard terminal feed.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_logs_pull_request_id"),
        "review_logs",
        ["pull_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # ── Step 2: Create HNSW index for vector similarity search ────────────────
    # Cannot be done through SQLAlchemy column definition — must be raw SQL.
    # HNSW = Hierarchical Navigable Small World.
    # Enables O(log n) approximate nearest-neighbor search instead of O(n).
    # vector_cosine_ops = use cosine distance (best for text embeddings).
    # m=16: each node connects to 16 neighbors.
    # ef_construction=64: thoroughness of index build (higher = better, slower).
    op.execute(
        """
        CREATE INDEX ix_embeddings_vector
        ON embeddings USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
        """
    )

    # ── Step 3: Seed ThirdPartyIntegration catalog rows ───────────────────────
    # These 3 rows define the integrations our platform supports.
    # Inserting here ensures they exist in every environment automatically.
    op.execute(
        """
        INSERT INTO third_party_integrations
            (id, name, display_name, description, auth_type,
             oauth_authorize_url, oauth_token_url, required_scopes,
             is_enabled, created_at, updated_at)
        VALUES
            (
                uuid_generate_v4(), 'github', 'GitHub',
                'Connect your GitHub account to review Pull Requests.',
                'oauth2',
                'https://github.com/login/oauth/authorize',
                'https://github.com/login/oauth/access_token',
                'repo read:user',
                TRUE, NOW(), NOW()
            ),
            (
                uuid_generate_v4(), 'jira', 'Jira Cloud',
                'Connect Jira to pull ticket context into reviews.',
                'oauth2',
                'https://auth.atlassian.com/authorize',
                'https://auth.atlassian.com/oauth/token',
                'read:jira-work offline_access',
                TRUE, NOW(), NOW()
            ),
            (
                uuid_generate_v4(), 'google', 'Google Workspace',
                'Connect Google to read design docs and feature specs.',
                'oauth2',
                'https://accounts.google.com/o/oauth2/v2/auth',
                'https://oauth2.googleapis.com/token',
                'https://www.googleapis.com/auth/drive.readonly',
                TRUE, NOW(), NOW()
            )
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_logs_pull_request_id"), table_name="review_logs")
    op.drop_table("review_logs")
    op.drop_index(
        op.f("ix_human_decisions_pull_request_id"), table_name="human_decisions"
    )
    op.drop_table("human_decisions")
    op.drop_index(op.f("ix_embeddings_source"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_pull_request_id"), table_name="embeddings")
    op.drop_table("embeddings")
    op.drop_index(op.f("ix_comments_status"), table_name="comments")
    op.drop_index(op.f("ix_comments_pull_request_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(
        op.f("ix_third_party_user_accounts_user_id"),
        table_name="third_party_user_accounts",
    )
    op.drop_table("third_party_user_accounts")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_pull_requests_user_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_status"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_third_party_integrations_name"), table_name="third_party_integrations"
    )
    op.drop_table("third_party_integrations")
    # ### end Alembic commands ###
